version: '2'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=message'
      - 'POSTGRES_PASSWORD=secret0987654321'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper1  # Ensure Zookeeper is started before Kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181  # Use the container name as the hostname
      KAFKA_CREATE_TOPIC: "my_topic:1:3"
